spring.application.name=educacionparatodos
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/educacion_para_todos
spring.datasource.username=postgres
spring.datasource.password=123456
server.port=${PORT:8085}

jwt.secret=educacion-para-todos-super-secret-key-2026-SEGURIDAD-JWT
jwt.expiration=3600000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=false

spring.jpa.open-in-view=false
spring.datasource.password=123