spring.application.name=educacionparatodos
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/educacion_para_todos
spring.datasource.username=postgres
spring.datasource.password=